# Generated by Django 5.0.7 on 2024-11-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('pages', models.IntegerField()),
                ('cover', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
